name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: Peaceful Ware/actions-gh-pages@v3
      with:
        branch: gh-pages  # На какой ветке размещаем
        folder: .  # Директория с файлами для развертывания
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
